project:
  name: text-analytics
  project_dir: ../
  datasets_dir: ../datasets

datasets:
  livedoor_news:
    dir: ../datasets/livedoor_news
    origin_dir: ../datasets/livedoor_news/raw/text
    processed_dir: ../datasets/livedoor_news/processed
    processed_csv_name: processed.csv
    class_label: labels.txt